# Generated by Django 5.1.5 on 2025-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="news_images/"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="news_images/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="news_images/"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="news_images/"),
                ),
                (
                    "image5",
                    models.ImageField(blank=True, null=True, upload_to="news_images/"),
                ),
            ],
        ),
    ]
