# Generated by Django 5.1.5 on 2025-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image10",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image6",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image7",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image8",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image9",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
