# Generated by Django 5.1.5 on 2025-01-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="notes_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
