# Generated by Django 5.1.5 on 2025-05-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
