# Generated by Django 5.1.5 on 2025-01-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plannerevent",
            name="when",
        ),
        migrations.AddField(
            model_name="plannerevent",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannerevent",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plannerevent",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional one-line description",
                max_length=200,
                null=True,
            ),
        ),
    ]
